In [1]:
import lhe_parser
import numpy as np

In [2]:
a,b,c,d,e = lhe_parser.parse_lhe("unweighted_events.lhe")

In [3]:
a.keys()

dict_keys(['Central scale variation', 'NNPDF23_lo_as_0130_qed'])

In [4]:
a['Central scale variation'][15]

{'MUR': 0.5,
 'MUF': 2.0,
 'DYN_SCALE': 4,
 'PDF': '247000',
 'contents': '\n MUR=0.5 MUF=2.0 dyn_scale_choice=sqrts  '}

In [5]:
b

array([[5, 1],
       [4, 1],
       [5, 1],
       ...,
       [5, 1],
       [5, 1],
       [5, 1]], shape=(10000, 2), dtype=int32)

In [6]:
c

array([[1.2775000e+03, 7.5888110e+01, 7.5467710e-03, ..., 1.2709793e+03,
        1.2710034e+03, 1.2506267e+03],
       [1.2775000e+03, 4.8511210e+01, 7.5467710e-03, ..., 1.0960970e+03,
        1.3525637e+03, 1.2648212e+03],
       [1.2775000e+03, 9.4683680e+01, 7.5467710e-03, ..., 1.0988324e+03,
        1.3155377e+03, 1.2601759e+03],
       ...,
       [1.2775000e+03, 9.1398700e+01, 7.5467710e-03, ..., 1.3213643e+03,
        1.3436258e+03, 1.3002160e+03],
       [1.2775000e+03, 9.1503660e+01, 7.5467710e-03, ..., 1.0984491e+03,
        1.3189796e+03, 1.2603018e+03],
       [1.2775000e+03, 9.4013460e+01, 7.5467710e-03, ..., 1.3193794e+03,
        1.3371488e+03, 1.2937264e+03]], shape=(10000, 149))

In [7]:
d

array([[    1,     4,    -1, ...,     0,   501,     0],
       [    1,    -4,    -1, ...,     0,     0,   501],
       [    1,    23,     2, ...,     2,     0,     0],
       ...,
       [10000,    23,     2, ...,     2,     0,     0],
       [10000,   -11,     1, ...,     3,     0,     0],
       [10000,    11,     1, ...,     3,     0,     0]],
      shape=(49895, 7), dtype=int32)

In [8]:
e

array([[   0.        ,    0.        ,    3.57784907, ...,    0.        ,
           0.        ,   -1.        ],
       [  -0.        ,   -0.        , -402.40698664, ...,    0.        ,
           0.        ,    1.        ],
       [   0.        ,    0.        , -398.82913757, ...,   75.88811403,
           0.        ,    0.        ],
       ...,
       [   0.        ,    0.        ,   71.11508526, ...,   94.01345625,
           0.        ,    0.        ],
       [  24.03513871,  -40.38368726,   34.24103714, ...,    0.        ,
           0.        ,    1.        ],
       [ -24.03513871,   40.38368726,   36.87404812, ...,    0.        ,
           0.        ,   -1.        ]], shape=(49895, 7))